# NUMPY 

So lets have a basic exercise on numpy. 

In [2]:
import numpy as np 

#### create an array of 10 tens 

In [4]:
# your code here-
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

#### Create an array of all the odd integers from 100 to 200

In [5]:
# your code here-
x=np.arange(101,200,2)
print(x)

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129 131 133 135
 137 139 141 143 145 147 149 151 153 155 157 159 161 163 165 167 169 171
 173 175 177 179 181 183 185 187 189 191 193 195 197 199]


#### Create a 3x3 identity matrix

In [6]:
# your code here-
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### write a code that gives the output given below
 ** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **



In [8]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [9]:
# your code here-


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Create a 4X4 matrix with values starting from 0

In [9]:
# your code here-
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Use NumPy to generate an array of 9 random numbers sampled from a standard normal distribution

In [10]:
# your code here-
np.random.randn(9)

array([ 1.24087031,  0.71573307, -0.59339412,  0.7291296 ,  0.63268884,
        0.29820082,  0.93049855,  0.30307941, -2.26858963])

In [12]:
j=np.arange(12,24).reshape(3,4)
j

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### on the given above array 'j' , perform the given questions. 

#### 1. Get the standard deviation of the values in mat

In [13]:
# your code here-
np.std(j)

3.452052529534663

#### 2. Get the sum of all the columns in mat

In [14]:
# your code here-
j.sum(axis=0)

array([48, 51, 54, 57])

#### 3. write a code that gives the following output given below.
** *Note! In order to not lose the output, make sure you don't code in the cell that is directly above the plot, there is an extra cell above that one which won't overwrite that plot!* **

In [16]:
x=np.arange(13,25,4).reshape(3,1)
print(x)

[[13]
 [17]
 [21]]


In [17]:
# your code here-


array([[13],
       [17],
       [21]])

#### 4. Get the sum of all the values in mat

In [17]:
# your code here-
x.sum()

51

# GLAD YOU COMPLETED THIS PART, GOOD LUCK AHEAD!!